### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [Simple0109/KIMOCHI#117]
@Simple0109 
お疲れ様です！
こちらMVPリリースレビューになります！

### 技術
LINEなどの外部APIとの通信やカリキュラムで扱ったsorceryではなくdeviceを使用しているところなど、技術にチャレンジしている印象を受けました。その点を踏まえて以下、技術面でのFBとなります。
- deviceを使用している関係かと思われるのですが、`app/controllers/users/`配下のファイルにコメントアウトが多く見受けられたので、ファイル自体を使用しない場合は削除、コメントアウトして置いておかなければいかない場合は、理由も残しておくと、第三者からコードを見られた時の印象が変わるかなと思いました。
- `app/controllers/requests_controller.rb`の`indexアクション`に記載してある`Kaminari.pagenate_array~`で始まるコードが部分的に重複しているかつ、少々可読性が気になるので、各**requestのstatusごと**にprivateに切り出して、そちらを呼び出してあげるとindexアクション内のコードもスッキリし、可読性が上がるかと思いました。（こちらをprivateに切り出す際は、statusの状態がメソッドの命名からわかるようなメソッド名にしてあげるといいかなと思います。）

### ユーザビリティ
基本的に、直感的にわかりやすいユーザビリティになっていると思います。
その中でも、少し気になった部分があるので、細かい点ですがFBとしてお伝えさせていただきます。

- TOPページに使い方説明があるかと思うのですが、**画像のどの部分が使い方説明の該当する場所**（招待リンクのボタンやクリアする条件が記載している場所）なのかをはっきりさせてあげると、視覚的にもわかりやすくなるかと思いました。
- ヘッダーの**ログアウト**のリンクですが、誤って押してしまった場合、そのままログアウトしてしまいますので、**ログアウト**リンクを押した後、**「ログアウトしますか？」の文言とともにアラートが出る**ような機能を入れると、誤ったアクションでログアウトせず、ユーザビリティがよくなるかと思いました。
- アプリ左がに表示されているの`「グループ」の文字をグループ遷移するリンクよりも大きく、「KIMOCHI」のタイトルよりも小さくする`と**所属しているグループが表示される場所**という認識がユーザーにも伝わりやすいかと思いました。

以上です！
全体的に、しっかりアプリとして機能していると思いました！
LGTMです！
上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。
スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by Simple0109** [comment]
@tmtkzk0823 
お疲れ様です。レビューありがとうございました！
本リリースは余裕を持って2/1の予定としていますが、1/20を目標に進めていきたいと思います

いくつかお聞きしたいことがあり、教えていただければ幸いです。
### 本番リリースの内容について
#35 #41 について余裕があればやってみたいなと思った機能であり、この機能の実装は本番リリース後、余裕があれば実装するという形でも良いものでしょうか？
※READMEに記述していない内容です

### パスワードリセット機能について
#33 に記述しているパスワードリセット機能なのですが、当初LINEログイン機能を実装する予定がなくdeviseによる認証ログインのみの予定でした。
現在、LINE通知機能を実装したため、結果的にLINEログインしないとLINE通知機能が使えない状態になっています。
であればいっそ通常の会員登録機能を削除し、会員登録する方法はLINE認証のみでもいいのかなと考えています。
こういった場合、会員登録機能はLINE認証のみでいいものか、それともLINE認証とdevise認証による二本立てにしたほうがいいいいものでしょうか？

お忙しいところ申し訳ありませんが、お時間あるときにご意見いただければ幸いです。よろしくお願いします。

**Comment by tmtkzk0823** [comment]
リリース日の件承知しました！
> 本番リリースの内容について
https://github.com/Simple0109/kimochi3/issues/35 https://github.com/Simple0109/kimochi3/issues/41 について余裕があればやってみたいなと思った機能であり、この機能の実装は本番リリース後、余裕があれば実装するという形でも良いものでしょうか？
※READMEに記述していない内容です

いいと思います！
面接で聞かれた際には、「今、追加で実装中」という内容の中に「本リリース後もしっかり開発している」ということを伝えられるようにしておくと安心かもです！

> パスワードリセット機能について
https://github.com/Simple0109/kimochi3/issues/33 に記述しているパスワードリセット機能なのですが、当初LINEログイン機能を実装する予定がなくdeviseによる認証ログインのみの予定でした。
現在、LINE通知機能を実装したため、結果的にLINEログインしないとLINE通知機能が使えない状態になっています。
であればいっそ通常の会員登録機能を削除し、会員登録する方法はLINE認証のみでもいいのかなと考えています。
こういった場合、会員登録機能はLINE認証のみでいいものか、それともLINE認証とdevise認証による二本立てにしたほうがいいいいものでしょうか？

個人的にはLINEログインが正常に動いているのであれば、一本に絞ってしまって良いかと思います！

**Comment by Simple0109** [comment]
@tmtkzk0823 
了解しました！ありがとうございます！
