### ISSUE TITLE
groupsテーブルにuser_idをreferences型で追加する方法

### ISSUE THREAD

**Issue by Simple0109** [Simple0109/KIMOCHI#166]
当初Groupモデルを作成するマイグレーションを作成した際、`groupsテーブル`に`user_id`を`references型`で設定をしておらず現在どの`User`が`Group`を作成したか判断することができない状況です…

そこで`groupsテーブル`に`user_id`カラムを`references型`で以下のようなマイグレーションファイルで追加しようと思っています
```ruby
class AddUserIdToGroups < ActiveRecord::Migration[7.0]

  def up
    add_reference :groups, :user, null: true, foreign_key: true
    
   #仮に私が作成したテストユーザーがUser.firstだった場合
    user_id = User.first.id
    Group.all.each do |group|
      group.update(user_id: user_id)
    end
  end

  def down
    remove_reference :groups, :user, index: true, foreign_key: true
  end
end
```

`user_id`カラムを`groupsテーブル`に追加すると、既存のGroupオブジェクトに関してエラーが発生すると思われるので、上記のような流れでGroupsテーブルにuser_idカラムを追加していいものか教えていただければ幸いです

なお現在、本番環境のUserオブジェクトはRUNTEQ講師の方々と、私のテストユーザーしかありません

なのでコンソールで`group`と`user`を特定後`group.update(user_id: user.id)`のように直打ちで対応できるのかな…とも思います…

**Comment by tmtkzk0823** [comment]
マイグレーションファイルにユーザーのuser_idを入れるコードを記述してしまうと、本番環境でデータをリセットする時等、少々面倒になるかと思うので、

1. groupsテーブルにuser_id（外部キー）を`null: true`オプションをつけた状態でマイグレーションファイルを作成
```
user_id = User.first.id
    Group.all.each do |group|
      group.update(user_id: user_id)
    end
こちらのコードは記載しないで大丈夫です！
```

2. 本番環境のコンソールを使って各groupsのデータにuser_idを入れる
3. groupsのuser_idのnull: true→ null: false に変更するマイグレーションファイルを作成 → 適用
の流れがいいかと思います！
